### ISSUE TITLE
use css with this?

### ISSUE THREAD

**Issue by Daedric1012** [edsnider/htmllabel#1]
Is it possible in it's current form to have a css file linked to it?

im using this in my app because i needed more control over each of the formatting for each page but still simple enough they can all use the same xaml page, so using this to allow html formatting in each of the text blocks from my database is the only solution i could think of but without a css file i may have created a whole lot more work just so a couple pages could have an extra flair.

**Comment by edsnider** [comment]
@daedric1991 that might/should work, but I didn't build it with that in mind and haven't tested that.
